import { site } from './site.mjs';
import { problems, services, demos, figmaText } from './data.mjs';
import { escape, paragraphs, tag, icon, button, motionButton, header, footer, cookieUI, contact, process as processSection, serviceCard } from './components.mjs';
import { legalContent } from './policies.mjs';
import { integrationStrip } from './integrations.mjs';
import { heroPoster } from './hero-poster.mjs';

const whisperWords = text => text.split(' ').map(word => `<span data-whisper-word>${escape(word)}</span>`).join(' ');

const aboutOpening = whisperWords('Aproximamos');

function aboutSection() {
  const rows = [['Eficiência', 'Cabeça de dono', 'Aprendizagem'], ['Ensinamento', 'Partilha', 'Agilidade', 'Velocidade'], ['Democracia', 'Dados ao alcance de todos'], ['Marcar gerações', 'Eficiência', 'Agilidade']];
  return `<section class="section about-section" id="sobre"><div class="container"><div class="section-heading">${tag('Sobre a dipanda')}<h2 class="about-statement" data-whisper><span class="about-line">${aboutOpening} ${whisperWords('pessoas, negócios e')}</span> <span class="about-line">${whisperWords('dados')} <span class="inline-symbol inline-symbol--blue" data-whisper-icon>${icon('/assets/figma/2-401-43766.svg')}</span> ${whisperWords('desenvolvemos')}</span> <span class="about-line">${whisperWords('soluções')} <span class="inline-symbol" data-whisper-icon>${icon('/assets/figma/2-401-bdfc9.svg')}</span> <span class="word-rotator" data-word-fit data-whisper-word data-word-rotator data-words='["personalizadas","escaláveis","confiáveis","inteligentes","flexíveis"]'><span class="word-width" aria-hidden="true">personalizadas</span><span class="word-current" data-word-current aria-hidden="true">personalizadas</span><span class="word-next" data-word-next aria-hidden="true"></span><span class="sr-only">personalizadas, escaláveis, confiáveis, inteligentes e flexíveis</span></span></span></h2></div>
  <div class="about-grid"><article class="about-card" data-reveal><h3>Quem somos?</h3><p>${escape(figmaText('2:457'))}</p></article><div class="values-card" data-loop-animation data-reveal aria-label="Os nossos valores: eficiência, cabeça de dono, aprendizagem, ensinamento, partilha, agilidade, velocidade, democracia, dados ao alcance de todos e marcar gerações.">${rows.map((row, index) => `<div class="marquee-row ${index % 2 ? 'marquee-row--reverse' : ''}" aria-hidden="true"><div class="marquee-track" data-pattern-length="${row.length}">${[0, 1].map(() => `<div class="marquee-group">${Array.from({ length: 4 }, () => row.map(value => `<span>${value}</span>`).join('')).join('')}</div>`).join('')}</div></div>`).join('')}</div><article class="about-card" data-reveal style="--stagger:120ms"><h3>Como?</h3><p>${escape(figmaText('5564:3278'))}</p></article></div></div></section>`;
}

function problemSection() {
  return `<section class="section problems-section" id="problema"><div class="container"><div class="section-heading" data-reveal>${tag('Problema')}<h2><em>Todas</em> as boas decisões começam<br class="desktop-break"> com bons <em>dados.</em></h2><p>${escape(figmaText('5545:3233'))}</p></div><div class="problem-tabs" role="tablist" aria-label="Problemas que resolvemos" data-problem-tabs>${problems.map((p, i) => `<button role="tab" type="button" id="tab-${p.slug}" aria-controls="panel-${p.slug}" aria-selected="${i === 0}" tabindex="${i === 0 ? 0 : -1}" data-tab-index="${i}">${escape(p.label)}</button>`).join('')}</div><div class="problem-panels" data-reveal>${problems.map((p, i) => `<div class="problem-panel" id="panel-${p.slug}" role="tabpanel" aria-labelledby="tab-${p.slug}" tabindex="0" ${i ? 'hidden' : ''}><div class="problem-content">${icon('/assets/figma/5545-3146-18db1.svg')}<h3>${escape(p.title)}</h3><div class="problem-description">${paragraphs(p.description)}</div>${motionButton('SAIBA MAIS', `/problemas/${p.slug}/`)}</div><div class="problem-image ${p.imageClass || ''}">${i === 0 ? '<img class="problem-underlay" src="/assets/figma/5545-3146-31f04.png" alt="" width="640" height="480" loading="lazy" aria-hidden="true">' : ''}<img src="${p.image}" alt="${escape(p.articleTitle)}" width="450" height="400" loading="lazy"></div></div>`).join('')}</div></div></section>`;
}

function demoCard(demo, index) {
  return `<article class="demo-card demo-card--showcase demo-card--${demo.slug}"><div class="demo-content"><h3>${escape(demo.title)}</h3><p>${escape(demo.description)}</p><a class="pill-link ${index === 0 ? 'pill-link--glass' : ''}" href="/demo/${demo.slug}/" aria-label="Ver demo: ${escape(demo.title)}">Ver demo<svg class="demo-link-arrow" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12h16M14 6l6 6-6 6"/></svg></a></div><div class="demo-image" aria-hidden="true"><img src="${demo.image}" alt="" width="640" height="450" loading="lazy"></div></article>`;
}

function demoSection() {
  return `<section class="section demos-section" id="demonstracao"><div class="container"><div class="section-heading section-heading--wide" data-reveal>${tag('Demonstração')}<h2>Explore <em>dashboards</em> desenvolvidos para responder às <em>perguntas</em> mais importantes de cada área do <em>negócio.</em></h2></div><div class="demo-grid demo-grid--showcase" data-reveal>${demos.map(demoCard).join('')}</div></div></section>`;
}

function serviceSection(all = false) {
  return `<section class="section services-section" id="servicos"><div class="container"><div class="section-heading" data-reveal>${tag('serviços')}<${all ? 'h1' : 'h2'}><em class="orange-bright">Soluções</em> adaptadas à realidade do <em class="orange-bright">seu negócio</em>.</${all ? 'h1' : 'h2'}>${all ? '<p>Escolha o ponto de partida que faz sentido para si. Definimos o âmbito, as entregas e o investimento depois de compreender o seu pedido.</p>' : button('ver todos serviços', '/servicos/')}</div><div class="services-${all ? 'grid' : 'carousel'}" data-pricing-group ${all ? '' : 'data-service-carousel tabindex="0" aria-label="Serviços — deslize para ver mais"'}>${services.map(serviceCard).join('')}</div>${all ? '' : '<div class="carousel-controls"><button class="carousel-arrow" type="button" aria-label="Serviços anteriores" data-carousel-prev><img src="/assets/figma/2-687-fb705.svg" width="24" height="24" alt=""></button><span class="carousel-progress" data-carousel-progress>01 — 06</span><button class="carousel-arrow" type="button" aria-label="Próximos serviços" data-carousel-next><img src="/assets/figma/2-687-fb705.svg" width="24" height="24" alt=""></button></div>'}</div></section>`;
}

function home() {
  return `<section class="hero" id="home">${header(true)}<div class="hero-surface">${heroPoster}<canvas class="hero-shader" data-hero-shader width="1" height="1" aria-hidden="true"></canvas><div class="hero-art" aria-hidden="true"><img class="hero-grid" src="/assets/figma/2-57-13a95.svg" alt=""><canvas class="hero-grid-canvas" width="1509" height="929" aria-hidden="true"></canvas><img class="hero-glow-top" src="/assets/figma/2-57-8d7af.svg" alt=""><img class="hero-glow-bottom" src="/assets/figma/2-57-dbb66.svg" alt=""><img class="hero-glow-shape" src="/assets/figma/2-57-9e3d0.svg" alt=""></div><div class="hero-copy"><span class="hero-badge">CONSULTORIA · TECNOLOGIA</span><h1 data-hero-text><span class="hero-text-loop"><span class="hero-text-loop-reveal"><span class="hero-text-loop-word">Transforme</span></span><span class="hero-text-loop-cursor" aria-hidden="true"></span></span> dados em<br><span>Decisões estratégicas</span></h1><p data-hero-text>Cruze os dados da tua empresa e descubra exatamente onde está a <span class="hero-highlight hero-highlight--orange">perder</span> tempo e dinheiro para maximizar os seus ganhos</p><div class="hero-buttons" data-hero-buttons>${motionButton('CONSULTORIA gratuita', '/#contacto')}<a class="pill-link pill-link--glass" data-soft-hover href="/#demonstracao">ver DEMO</a></div></div><div class="hero-tools"><p>Ferramentas que ligamos aos seus dados</p>${integrationStrip()}</div></div></section>
  ${aboutSection()}${problemSection()}${processSection()}${demoSection()}${serviceSection()}${contact()}`;
}

function innerHero(label, title, description, image = '', extra = '') {
  return `<section class="inner-hero"><div class="container"><a class="breadcrumb" href="/">Home <span aria-hidden="true">↗</span></a><div class="inner-hero-grid ${image ? '' : 'inner-hero-grid--text'}"><div>${tag(label)}<h1>${title}</h1><div class="inner-description">${paragraphs(description)}</div>${extra}</div>${image ? `<div class="inner-hero-image"><img src="${image}" width="640" height="620" alt="${escape(label)}" fetchpriority="high"></div>` : ''}</div></div></section>`;
}

function problemArticle(problem) {
  const headings = ['Os números da sua empresa não deviam mudar conforme o ficheiro que abre', 'Uma alteração pode passar despercebida', 'Todos os números parecem certos até deixarem de coincidir.', 'E se a sua empresa trabalhasse com uma visão comum?', 'Descubra onde a sua empresa está a perder clareza'];
  const article = typeof problem.article === 'string' ? problem.article.trim().split(/\n\s*\n/).map(p => p === '[Pedir um diagnóstico]' ? button('Pedir um diagnóstico', '/#contacto') : headings.includes(p) ? `<h2>${escape(p)}</h2>` : `<p>${escape(p).replaceAll('\n', '<br>')}</p>`).join('') : problem.article.map(([title, body]) => `<h2>${escape(title)}</h2><p>${escape(body)}</p>`).join('') + button('Pedir um diagnóstico', '/#contacto');
  return `${innerHero(problem.label, escape(problem.articleTitle), problem.description, problem.image, button('Pedir um diagnóstico', '/#contacto'))}<section class="section article-section"><div class="container article-content" data-reveal>${article}</div></section><section class="section related-section"><div class="container"><div class="section-heading section-heading--left" data-reveal>${tag('Continue a explorar')}<h2>Temas semelhantes</h2></div><div class="related-grid">${problems.filter(p => p.slug !== problem.slug).map((p, i) => `<a class="related-card ${i === 0 ? 'related-card--lime' : ''}" href="/problemas/${p.slug}/" data-reveal><span class="related-top"><h3>${escape(p.title)}</h3><span class="related-arrow" aria-hidden="true">↗</span></span><p>${escape(p.summary)}</p><img src="${p.image}" width="400" height="324" loading="lazy" alt="${escape(p.articleTitle)}"></a>`).join('')}</div></div></section>${contact()}`;
}

function companyPage() {
  return `${innerHero('Sobre a dipanda', 'Pessoas, negócios<br>e <em>dados.</em>', figmaText('2:457'), '', button('Vamos conversar', '/#contacto'))}${aboutSection()}${processSection()}${contact()}`;
}

function serviceDetail(service) {
  return `${innerHero('Solução e Serviços', escape(service.title), service.description, '', button('Pedir uma proposta', '/#contacto'))}<section class="section service-detail"><div class="container"><div class="detail-grid"><article class="detail-card detail-card--lime" data-reveal>${tag('O seu ponto de partida')}<h2>Para quem é indicado?</h2><p>${escape(service.audience)}</p></article><article class="detail-card" data-reveal>${tag('Âmbito da solução')}<h2>O que podemos fazer</h2><ul class="check-list">${service.benefits.map(b => `<li><span aria-hidden="true">✓</span>${escape(b)}</li>`).join('')}</ul></article></div><div class="section-heading" data-reveal>${tag('Da ideia à utilização')}<h2>Uma entrega <em>clara.</em></h2><p>O âmbito é definido na proposta, de acordo com as necessidades do seu projeto.</p></div><ol class="deliverables">${service.deliverables.map((d, i) => `<li data-reveal><span>0${i + 1}</span><h3>${escape(d)}</h3></li>`).join('')}</ol><div class="service-investment" data-reveal><div>${tag('Investimento')}<h2>Sob consulta.</h2><p>O valor depende do âmbito, das integrações e das entregas acordadas. Começamos por uma conversa para compreender o que precisa.</p></div>${button('Consultar a equipa', '/#contacto', 'lime')}</div></div></section>${service.slug === 'produtos-dipanda' || service.slug === 'solucoes-analytics' ? demoSection() : ''}${contact()}`;
}

function demoPage(demo) {
  return `${innerHero('Demonstração', escape(demo.title), demo.description, demo.image, button('Explorar a demonstração', '#demo-interativa', 'dark'))}<section class="section demo-detail"><div class="container"><div class="detail-grid"><article class="detail-card detail-card--lime" data-reveal>${tag('A pergunta que importa')}<h2>${escape(demo.question)}</h2><p>${escape(demo.audience)}</p></article><article class="detail-card" data-reveal>${tag('O que pode analisar')}<h2>Informação que orienta a decisão.</h2><ul class="check-list">${demo.capabilities.map(c => `<li><span aria-hidden="true">✓</span>${escape(c)}</li>`).join('')}</ul></article></div>
  <div class="section-heading" id="demo-interativa" data-reveal>${tag('Experimente')}<h2>Explore uma visão de <em>exemplo.</em></h2><p>Esta demonstração interativa utiliza dados fictícios. Selecione um período para ver os indicadores e o detalhe.</p></div>
  <div class="dashboard-demo" data-dashboard="${demo.slug}" data-reveal><div class="dashboard-top"><div><span class="demo-live-label"><i aria-hidden="true"></i>DADOS DE EXEMPLO</span><h3>${escape(demo.title)}</h3></div><div class="dashboard-actions"><label for="demo-period">Período<select id="demo-period" data-demo-period><option value="quarter">Último trimestre</option><option value="month">Último mês</option><option value="year">Último ano</option></select></label><button type="button" class="pill-link" data-demo-download>Exportar CSV <span aria-hidden="true">↓</span></button></div></div><div class="dashboard-metrics" aria-live="polite" data-demo-metrics></div><div class="dashboard-chart"><div class="chart-heading"><h4>Evolução por período</h4><span>Dados fictícios · EUR / unidades</span></div><div class="bar-chart" data-demo-chart role="img" aria-label="Gráfico com dados de exemplo"></div></div><div class="dashboard-table"><table><caption>Detalhe dos indicadores de exemplo</caption><thead><tr><th scope="col">Indicador</th><th scope="col">Período atual</th><th scope="col">Período anterior</th><th scope="col">Variação</th></tr></thead><tbody data-demo-table></tbody></table></div><p class="sr-only" role="status" data-demo-status></p></div>
  <div class="technology-panel" data-reveal>${tag('Tecnologias e implementação')}<h2>Uma solução pensada para os seus dados.</h2><p>Uma implementação deste tipo pode ligar ERP, CRM, ficheiros Excel e bases de dados. A preparação e a transformação dos dados, o modelo analítico e a ferramenta de visualização são definidos depois de avaliar a sua realidade. Ferramentas como SQL, Python e Power BI podem integrar a solução; a escolha faz parte da proposta técnica.</p><div class="technology-chips"><span>Integração de fontes</span><span>Qualidade dos dados</span><span>Modelação</span><span>Dashboards</span></div><p class="technology-note">A demonstração desta página foi implementada em HTML, CSS e JavaScript. As imagens de pré-visualização são as referências do design e não apresentam dados reais de clientes.</p></div></div></section>${contact()}`;
}

function legalPage(type) {
  const content = legalContent(type);
  return `${innerHero('Informação legal', escape(content.title), `Última atualização: ${site.updatedAt}`)}<section class="section legal-section"><div class="container legal-layout"><nav class="legal-nav" aria-label="Índice da política">${content.sections.map((section, i) => `<a href="#legal-${i}">${escape(section.title)}</a>`).join('')}${type === 'cookies' ? '<button class="plain-button" data-cookie-settings>Gerir cookies</button>' : ''}</nav><div class="legal-content">${content.sections.map((section, i) => `<section id="legal-${i}"><h2>${escape(section.title)}</h2>${section.html || paragraphs(section.body)}</section>`).join('')}</div></div></section>`;
}

export const pages = {
  '/': { title: 'Dipanda — Transforme dados em decisões estratégicas', description: 'Consultoria tecnológica, dados e Business Intelligence. Ligue informação, acompanhe resultados e tome decisões com mais clareza e confiança.', body: home },
  '/sobre': { title: 'Sobre a Dipanda', description: figmaText('2:457'), body: companyPage },
  '/servicos': { title: 'Soluções e Serviços — Dipanda', description: 'Consultoria BI, soluções analytics, atendimento e automação, desenvolvimento SaaS e pedidos personalizados.', body: () => serviceSection(true) + contact() },
  '/contacto': { title: 'Contacto — Dipanda', description: 'Vamos falar sobre os seus dados. Contacte a equipa Dipanda.', body: () => contact(true, true) },
  '/termos-e-condicoes': { title: 'Termos e Condições — Dipanda', description: 'Condições de utilização do site e dos serviços da Dipanda.', body: () => legalPage('terms') },
  '/politica-de-privacidade': { title: 'Política de Privacidade — Dipanda', description: 'Como tratamos os seus dados pessoais e como pode exercer os seus direitos.', body: () => legalPage('privacy') },
  '/politica-de-cookies': { title: 'Política de Cookies — Dipanda', description: 'Conheça os cookies do site e controle as suas preferências.', body: () => legalPage('cookies') },
  '/404': { title: 'Página não encontrada — Dipanda', description: 'A página que procura não está disponível.', body: () => innerHero('404', 'Vamos encontrar<br>o caminho <em>certo.</em>', 'A página que procura não está disponível. Pode regressar à página inicial ou falar com a nossa equipa.', '', button('Voltar à Home', '/')) }
};
problems.forEach(problem => { pages[`/problemas/${problem.slug}`] = { title: `${problem.articleTitle} — Dipanda`, description: problem.summary, body: () => problemArticle(problem) }; });
services.forEach(service => { pages[`/servicos/${service.slug}`] = { title: `${service.title} — Dipanda`, description: service.description, body: () => serviceDetail(service) }; });
demos.forEach(demo => { pages[`/demo/${demo.slug}`] = { title: `${demo.title} — Dipanda`, description: demo.description, body: () => demoPage(demo) }; });

export function renderPage(route) {
  const page = pages[route] || pages['/404'];
  const homePage = route === '/';
  const siteUrl = (process.env.SITE_URL || '').replace(/\/$/, '');
  const absolute = siteUrl ? `${siteUrl}${route === '/' ? '/' : route + '/'}` : '';
  return `<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content"><meta name="theme-color" content="${homePage ? '#004cd3' : '#131313'}"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}">${absolute ? `<link rel="canonical" href="${escape(absolute)}"><meta property="og:url" content="${escape(absolute)}">` : ''}<meta property="og:type" content="website"><meta property="og:locale" content="pt_PT"><meta property="og:site_name" content="Dipanda"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="/assets/brand/dipanda-favicon.svg"><link rel="preload" href="/fonts/plus-jakarta-500.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/css/site.css"><link rel="stylesheet" href="/css/navigation.css"><link rel="stylesheet" href="/css/buttons.css"><link rel="stylesheet" href="/css/about.css">${homePage ? '<link rel="stylesheet" href="/css/hero.css">' : ''}<link rel="stylesheet" href="/css/refinements.css"><link rel="stylesheet" href="/css/brand.css">${homePage || route === '/sobre' ? '<link rel="stylesheet" href="/css/process.css">' : ''}${homePage ? '<link rel="stylesheet" href="/css/hero-refresh.css">' : ''}${route === '/404' ? '<meta name="robots" content="noindex">' : ''}</head><body data-page="${escape(route)}"><a class="skip-link" href="#main">Saltar para o conteúdo</a>${homePage ? '' : header()}<main id="main">${page.body()}</main>${footer()}${cookieUI()}<script type="module" src="/js/app.js"></script></body></html>`;
}
