import { site } from './site.mjs';

const contact = `Para qualquer questão, escreva para ${site.email} ou contacte ${site.phone}.`;
const identity = `O site Dipanda é apresentado pela marca ${site.legalName}.${site.taxId ? ` NIF: ${site.taxId}.` : ''}${site.address ? ` Morada: ${site.address}.` : ''} ${contact}`;

export function legalContent(type) {
  if (type === 'cookies') return {
    title: 'Política de Cookies',
    sections: [
      { title: '1. O que são cookies?', body: 'Cookies são pequenos ficheiros que o navegador guarda no seu dispositivo. Neste site, servem para registar a sua escolha de privacidade e, se autorizar, lembrar a sua preferência de animações.' },
      { title: '2. Cookies utilizados', html: '<div class="table-scroll"><table class="policy-table"><thead><tr><th>Nome</th><th>Finalidade</th><th>Categoria</th><th>Duração</th></tr></thead><tbody><tr><td><code>dipanda_consent</code></td><td>Regista a escolha de cookies, a data e a versão do consentimento.</td><td>Essencial</td><td>180 dias</td></tr><tr><td><code>dipanda_preferences</code></td><td>Lembra se escolheu pausar as animações.</td><td>Funcional, opcional</td><td>180 dias</td></tr></tbody></table></div><p>São cookies próprios, aplicáveis a todo o site. O cookie funcional só é criado depois de aceitar esta categoria. O site não instala cookies de publicidade nem ferramentas de análise de terceiros.</p>' },
      { title: '3. Escolher e retirar o consentimento', body: 'Na primeira visita, pode aceitar todos os cookies, rejeitar os opcionais ou personalizar a escolha. Os cookies opcionais estão desativados por defeito. Rejeitar não impede a navegação, a consulta de demonstrações ou o contacto com a equipa.\n\nPode abrir “Gerir cookies” no rodapé e alterar a escolha a qualquer momento. Ao desativar os cookies funcionais, o respetivo cookie é eliminado. A escolha essencial é conservada para respeitar a sua decisão. Quando expirar, pedimos uma nova escolha.' },
      { title: '4. Definições do navegador', body: 'Também pode bloquear ou apagar cookies nas definições do navegador. Se bloquear todos os cookies, o site não conseguirá lembrar a sua escolha e poderá voltar a mostrar o pedido de consentimento. As funcionalidades opcionais permanecem desativadas quando não existe uma escolha válida.' },
      { title: '5. Contactos e alterações', body: `${identity}\n\nSe forem acrescentadas outras tecnologias ou alteradas as finalidades, esta política e o pedido de consentimento devem ser atualizados antes da sua ativação. Consulte também a Política de Privacidade.` }
    ]
  };
  if (type === 'privacy') return {
    title: 'Política de Privacidade',
    sections: [
      { title: '1. Quem trata os dados', body: identity },
      { title: '2. Dados e finalidades', body: 'Quando nos contacta, recebemos o nome, o endereço de e-mail e a mensagem que decide enviar. Utilizamos estes dados para responder ao seu pedido, compreender as necessidades do projeto e preparar uma proposta quando a solicitar. Evite incluir na mensagem informação sensível ou dados pessoais de terceiros que não sejam necessários.\n\nO servidor de alojamento pode tratar dados técnicos necessários à comunicação, como endereço IP e informação do navegador, para disponibilizar e proteger o site. As escolhas de cookies e de animações são guardadas no seu navegador, segundo a Política de Cookies. As demonstrações apresentam dados fictícios e não pedem acesso aos seus sistemas.' },
      { title: '3. Fundamentos do tratamento', body: 'O tratamento de pedidos de proposta e de informações sobre serviços assenta nas diligências pré-contratuais que solicita. A resposta a outros contactos e a proteção do site assentam no interesse legítimo em gerir a comunicação e manter o serviço seguro. O cumprimento de obrigações legais pode exigir tratamentos adicionais. Os cookies funcionais dependem do seu consentimento, que pode retirar a qualquer momento.' },
      { title: '4. Conservação', body: 'Os contactos sem contratação são conservados apenas pelo tempo necessário para responder e acompanhar o pedido, com revisão ao fim de 12 meses após a última interação. Se existir uma relação contratual, os dados necessários ao contrato e à faturação seguem os prazos legais aplicáveis. Pedidos de eliminação são avaliados à luz das obrigações legais e da necessidade de defesa de direitos.\n\nOs cookies indicados na Política de Cookies expiram ao fim de 180 dias, podendo ser eliminados antes nas definições de privacidade.' },
      { title: '5. Prestadores e transferências', body: 'Podemos recorrer a prestadores de alojamento e de correio eletrónico para disponibilizar o site e responder aos contactos. O acesso deve limitar-se às finalidades acordadas e estar sujeito a obrigações de proteção de dados. Não vendemos os seus dados pessoais nem usamos este formulário para subscrever automaticamente comunicações comerciais.\n\nSe um prestador implicar transferências para fora do Espaço Económico Europeu, devem ser aplicadas as garantias exigidas pela legislação de proteção de dados, como decisões de adequação ou cláusulas contratuais-tipo, quando aplicáveis. Pode pedir informações sobre os prestadores e as garantias através do contacto acima.' },
      { title: '6. Os seus direitos', body: `Pode solicitar acesso, retificação, apagamento, limitação, portabilidade ou oposição ao tratamento, quando aplicáveis, através de ${site.email}. Pode ser necessária informação proporcional para confirmar a identidade. Pode retirar o consentimento dos cookies em “Gerir cookies”, sem afetar a licitude do tratamento anterior.\n\nTem também o direito de apresentar uma reclamação à autoridade de controlo competente. Em Portugal, pode contactar a Comissão Nacional de Proteção de Dados.` },
      { title: '7. Segurança e ligações externas', body: 'Aplicamos medidas proporcionais para limitar o acesso à informação e proteger a comunicação. Nenhum sistema elimina todos os riscos. Os links para páginas externas estão sujeitos às políticas dessas páginas. O site não toma decisões automatizadas com efeitos jurídicos sobre os visitantes nem cria perfis de publicidade.' },
      { title: '8. Atualizações', body: 'Esta política pode ser atualizada para refletir alterações no funcionamento do site, nos prestadores ou nas obrigações aplicáveis. A data da versão aparece no início da página. Alterações que dependam de consentimento serão apresentadas antes de ativar o tratamento correspondente.' }
    ]
  };
  return {
    title: 'Termos e Condições',
    sections: [
      { title: '1. Identificação e âmbito', body: `${identity}\n\nEstes termos regulam a utilização do site. A contratação de serviços é regulada pela proposta e pelo contrato específico aceites pelas partes, incluindo âmbito, preço, prazos e responsabilidades.` },
      { title: '2. Utilização do site', body: 'Pode consultar as informações e demonstrações para conhecer as soluções Dipanda. Deve utilizar o site de forma lícita, sem interferir no funcionamento, tentar aceder a áreas não autorizadas, introduzir código malicioso ou submeter conteúdos fraudulentos. Os pedidos enviados devem conter informação verdadeira e pertinente.' },
      { title: '3. Conteúdos e demonstrações', body: 'Os conteúdos apresentam os serviços de forma geral. As demonstrações utilizam dados fictícios e servem para ilustrar possibilidades de análise; não constituem aconselhamento financeiro nem previsões sobre os resultados do seu negócio. Os valores apresentados não são preços ou compromissos de desempenho.\n\nAs tecnologias, integrações e funcionalidades de cada projeto são confirmadas na proposta técnica. Um pedido de contacto ou de demonstração não constitui um contrato.' },
      { title: '4. Propostas e contratação', body: 'Os serviços indicados como “Sob consulta” são avaliados de acordo com a necessidade, o âmbito e a complexidade do projeto. A proposta deve identificar as entregas, os prazos, o investimento, os impostos aplicáveis, as condições de pagamento e os termos de suporte. A contratação só ocorre após a aceitação das condições acordadas.\n\nEventuais direitos imperativos de consumidores, incluindo informação pré-contratual e livre resolução quando aplicável, não são limitados por estes termos.' },
      { title: '5. Propriedade intelectual', body: 'A marca, o design, os textos e os restantes conteúdos pertencem aos respetivos titulares. Pode consultá-los e partilhar ligações ao site. A reprodução ou utilização comercial dos conteúdos exige autorização, salvo nos casos legalmente permitidos. Os direitos sobre entregas de projetos, licenças de software e materiais de terceiros são definidos no respetivo contrato.' },
      { title: '6. Disponibilidade e responsabilidade', body: 'Procuramos manter a informação atualizada e o site disponível. Podem ocorrer interrupções por manutenção, falhas técnicas ou circunstâncias externas. Não garantimos a disponibilidade contínua nem resultados comerciais concretos a partir da utilização das demonstrações. Nenhuma disposição exclui responsabilidades que a lei não permita excluir.' },
      { title: '7. Privacidade e cookies', body: 'O tratamento de dados pessoais está descrito na Política de Privacidade. Os cookies e as formas de aceitar, rejeitar e alterar a escolha estão descritos na Política de Cookies. A consulta do site não obriga a aceitar cookies opcionais.' },
      { title: '8. Contactos, alterações e lei aplicável', body: `${contact}\n\nPodemos atualizar estes termos, indicando a data da nova versão. As condições já acordadas em contrato não são alteradas automaticamente por uma atualização do site. A legislação portuguesa aplica-se à utilização deste site, sem prejuízo de normas imperativas aplicáveis e dos direitos dos consumidores. Em caso de conflito, procuramos uma solução através de contacto direto, preservando o recurso às entidades e aos tribunais competentes.` }
    ]
  };
}
